version: '3.8'

services:
  ai:
    restart: always
    build:
        context: ./services/AI
    command: python3 main.py #gunicorn main:app --bind 0.0.0.0:4999 -w 4 -k uvicorn.workers.UvicornWorker
    volumes:
      - ./services/AI/:/home/app/
    ports:
      - 4999:4999